version: '3'
services:
  gem:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/takeruun_gem
      - bundle:/usr/local/bundle
    command: bundle install

volumes:
  bundle: